version: 2.1
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn
      - run: yarn build-electron-win
      - run: mkdir /tmp/artifacts
      - run: mv -t /tmp/artifact dist/*.exe
      - store_artifacts:
          path: /tmp/artifacts
  build_linux:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: yarn
      - run: yarn build-electron-linux
      - run: mkdir /tmp/artifacts
      - run: mv -t /tmp/artifacts dist/*.snap dist/*.AppImage
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  build:
    jobs:
      - hold:
          type: approval
      - build_windows:
          requires:
            - hold
      - build_linux:
          requires:
            - hold
