version: 2.1
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn
      - run: yarn electron-ci
      - run: yarn build-electron-win
  build_linux:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: yarn
      - run: yarn electron-ci
      - run: yarn build-electron-linux

workflows:
  build:
    jobs:
      - build_windows
      - build_linux